services:
  app:
    image: amazoncorretto:21
    networks:
      - restricted
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/build
      - /app/.gradle
    working_dir: /app
    command: sh -c "./gradlew build --project-cache-dir libs --gradle-user-home libs --offline && java -jar build/libs/gradle-offline-demo-0.0.1-SNAPSHOT.jar"

networks:
  restricted:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
